# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='acudiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Profile'),
        ),
    ]
