# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_estudiantes_electivas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS')])),
                ('token', models.CharField(max_length=144)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Profile')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.Categorias'),
            preserve_default=False,
        ),
    ]
