# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20160617_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucional',
            name='horarios',
            field=models.TextField(default='Lunes a Viernes 8 a 12 - 2 a 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokens',
            name='device',
            field=models.CharField(default='mi android', max_length=144),
            preserve_default=False,
        ),
    ]
