# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 05:12
from __future__ import unicode_literals

import app.inicio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20160617_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenido',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='electivas',
            field=models.ManyToManyField(blank=True, null=True, related_name='eleconcate', to='inicio.Categorias'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to=app.inicio.models.Galeria.uploadImg),
        ),
    ]
