# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20160621_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Docente')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='electivas',
            field=models.ManyToManyField(related_name='eleconcate', to='inicio.Categorias'),
        ),
    ]
