# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20160707_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=244),
        ),
    ]
