# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_auto_20160710_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='remitente',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='inicio.Profile'),
            preserve_default=False,
        ),
    ]
