# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_notificaciones_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 10, 21, 38, 1, 650199, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
