# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_contenido_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Megusta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'me_gusta',
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='autor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inicio.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='megusta',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Contenido'),
        ),
        migrations.AddField(
            model_name='megusta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Profile'),
        ),
    ]
