# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_auto_20160710_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Profile'),
        ),
    ]
