# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_auto_20160711_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cedula',
            field=models.CharField(max_length=144),
        ),
    ]
