# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 01:38
from __future__ import unicode_literals

import app.inicio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_auto_20160726_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='media/img/usuarios/adefault.png', upload_to=app.inicio.models.Profile.ImageProfile),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
